### ISSUE TITLE
Original window stay focused, when openning another project in a new window.

### ISSUE THREAD

**Issue by PsychodelEKS** [krasa/FrameSwitcher#8]

**Comment by krasa** [comment]
What OS?

**Comment by PsychodelEKS** [comment]
win7x64 Ultimate sp1 (latest updates), java 8#31, phpstorm 139.1348.
switching between open frames works fine.

**Comment by krasa** [comment]
I have those myself and it works fine. The thing is, it will put focus into Project view. That is just IntelliJ thing. 

There is one thing i found about switching open frames now - when not using Enter for selecting the frame, but just double clicking Alt+F2 -> it will switch a frame but pressing another key is then required, otherwise Windows will not really switch the focus - magic.

If you had a Linux, then I would not be surprised at all.

**Comment by PsychodelEKS** [comment]
I've played around a bit with it (some heavy open/close testing), may be there is some race condition, it does work fine some times, especially with smaller projects, those do stably open&focus. Larger open, but are not focused afterwards.
Openning through "File -> Reopen Project" works fine every time with all projects.

**Comment by krasa** [comment]
That is strange, because those actions for reopening of a project are identical to those which are in main menu. 
You could try one thing, ctrl+shift+a | Reopen Project - it will open a popup, so you would have the same actions and the same way of executing them as in my plugin.

Yep, there might be some bug for larger project, or for some specific framework.

**Comment by PsychodelEKS** [comment]
Invoking switching through ctrl+shift+a also does not work some times =(
It may be than related to "always on top" issue in IDE, that is known.
It's sad, but the issue can be closed, it is definetely not plugin related =)

thanks for your help'n'development

**Comment by krasa** [comment]
thanks
